# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10deb96660ea785a9c5fa0ce57a20905be4e3d87e14e7e088fb1f6a0b48b9ab705874f44c75805d19eba7674a7560c35519c59cff1a388ef9d96ad60996c7242

test:
  secret_key_base: 93f4c43c58753ed9573dcc013dfb566ed8e5b38232e53f62b12e363b10187c35320b0861f46b0838a05fc1dc40a0236aff8e40ea2e2224fbc7bec2f137c65e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
